services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: ./server
    container_name: flask_app
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - ./server:/app/src
